### ISSUE TITLE
local_configuration

### ISSUE THREAD

**Issue by floswald** [jdingel/DavisDingelMonrasMorales#1]
hi there,

thanks for making this code so easily accessible. I tried to run the local setup script but hit a wall quite quickly: folder `/isoindex_venueFE/code/` seems to be missing from the repo?
cheers

```
➜  DavisDingelMonrasMorales git:(master) ✗ ./local_configuration.sh
Please indicate the number of cores available locally: 6
ln: ./isoindex_venueFE/code/: No such file or directory
./local_configuration.sh: line 12: cd: ./isoindex_venueFE/code/: No such file or directory
find: *.sbatch: No such file or directory
grep: *.sbatch: No such file or directory
ln: ./predictvisits_estsmp_FE/code/: No such file or directory
./local_configuration.sh: line 12: cd: ./predictvisits_estsmp_FE/code/: No such file or directory
find: *.sbatch: No such file or directory
grep: *.sbatch: No such file or directory
```

**Comment by jdingel** [comment]
Florian,
I apologize for my very tardy response. I did not see a notification when you opened this issue. Those folders should not be in the repo; the configuration script mistakenly included them in the list of folders. Please see my latest commit (951507c), which corrects the local setup script.
Thanks!
